### ISSUE TITLE
New GEOJSON Multi-Polygon Field in AOITrack-Earthquake Datasets

### ISSUE THREAD

**Issue by riverma** [aria-jpl/coseismic_enumerator#13]
**Is your feature request related to a problem? Please describe.**
The [Displacement Evaluator](https://github.com/aria-jpl/coseismic_usgs_neic_evaluator) is generating new GEOJSON multi-polygon bounding "box" data that is water-masked into a new field within the generated `aoitrack-earthquake` datasets. 

**Describe the solution you'd like**
The Enumerator should use the field `water_mask_geojson_polygon` as opposed to the legacy bounding box field for water-masked multi-polygon bounding boxes representing the AOI. Note the legacy `geojson_polygon` will still be available, though will not be water masked. 

**Describe alternatives you've considered**
n/a

**Additional context**
Reach out to @marjo-luc for any other details.

**Comment by al-niessner** [comment]
@marjo-luc 

Is the new item in metadata or in _source?

**Comment by marjo-luc** [comment]
@al-niessner It should be in source at this path: 

_source: ["metadata"]["event_metadata"]["water_masked_geojson_polygon"]

[Sample Updated AOITRACK](https://mamba-grq.aria.hysds.io/search/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsiZGF0YXNldF90eXBlLnJhdyI6ImFyZWFfb2ZfaW50ZXJlc3QifX0seyJ0ZXJtIjp7ImRhdGFzZXQucmF3IjoiYW9pdHJhY2stZWFydGhxdWFrZSJ9fSx7InF1ZXJ5X3N0cmluZyI6eyJxdWVyeSI6Il9pZDpcIkFPSVRSQUNLX2VxX3VzZ3NfbmVpY19wZGxfdXM3MDAwZDBnbl81NV9CYW5kYXJlX0xlbmdlaF9JcmFuXzEzMFwiIiwiZGVmYXVsdF9vcGVyYXRvciI6Ik9SIn19XX19LCJzb3J0IjpbeyJfdGltZXN0YW1wIjp7Im9yZGVyIjoiZGVzYyJ9fV0sImZpZWxkcyI6WyJfdGltZXN0YW1wIiwiX3NvdXJjZSJdfQ==)

<img width="446" alt="Screen Shot 2021-04-21 at 1 57 18 PM" src="https://user-images.githubusercontent.com/47004511/115620444-09f31e00-a2aa-11eb-81a6-6969d896399c.png">
