### ISSUE TITLE
Acquisition List ID field too long to process downstream

### ISSUE THREAD

**Issue by riverma** [aria-jpl/coseismic_enumerator#19]
**Describe the bug**
The HySDS `job-coseismic_product-s1gunw-slc_localizer:main` Localizer PGE failed to process an Enumerator `S1-COSEISMIC-GUNW-acq-list-event-iter` acquisition list in the download phase. Specifically, the downstream Localizer PGE complained it was attempting to create a download directory that was too long in terms of its file name. 

Upon investigation of the code, the Localizer PGE uses the `job_id` field that derives from an `id` from an Enumerator acquisition list to create a directory for SLC downloads. [This line fails](https://github.com/hysds/hysds/blob/ccaf62b8bb11dfe8a51c4944a4190d3876f0af59/hysds/job_worker.py#L817) during runtime with the following error:

```
Traceback (most recent call last):
  File "/data/export/home/hysdsops/verdi/ops/hysds/hysds/job_worker.py", line 759, in run_job
    makedirs(job_dir)
  File "/data/export/home/hysdsops/verdi/ops/hysds/hysds/utils.py", line 228, in makedirs
    os.makedirs(dir, mode)
  File "/export/home/hysdsops/verdi/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/data/work/jobs/2021/04/26/06/12/coseismic_product-s1gunw-slc_localizer__main-S1-COSEISMIC-GUNW-acq-list-event-iter_3+3--AOITRACK_eq_usgs_neic_pdl_us7000d0gn_55_Bandare_Lengeh_Iran_130--acquisition-S1A_IW_SLC__1SDV_20210215T142520_20210215T142548_036602_044CD2_BA7A-esa_scihub-20210426T061235.142811Z'
```

**To Reproduce**
1. Go to GRQ and facet upon the latest Coseismic Enumerator `S1-COSEISMIC-GUNW-acq-list-event-iter` datasets
2. Run an On-Demand job against the `coseismic_product-s1gunw-slc_localizer__main` PGE
3. In Mamba (Resource Manager) see how the Localizer fails with the above error

**Expected behavior**
We should really do the following to minimize overall code impact:
1. Shorten the `S1-COSEISMIC-GUNW-acq-list-event-iter` dataset's `id` field to be within the `255 bytes` max length for Unix file names
2. Ensure the `S1-COSEISMIC-GUNW-acq-list-event-iter` dataset's `id` field is kept unique

Recommendation for the above: we should use an `id` naming pattern for `S1-COSEISMIC-GUNW-acq-list-event-iter` dataset entries that reflects the pattern used for the ARIA standard-pipeline. For example, here's an acquisition list ID from the standard pipeline: `S1-GUNW-acqlist-RM-M1S3-TN018-20191028T232823-20191004T232730-poeorb-00d5`. Notice how there are two key components to this unique ID: (1) the date range over which the acqlists apply, and (2) a unique hash

**Screenshots**
n/a

**Environment (please complete the following information):**
- ARIA Factotum VM

**Additional context**
@cmarshak might have more information regarding how the standard pipeline's `id` field was designed (according to @marjo-luc). There may be science use case reasons why an ID like that would be useful.

**Comment by cmarshak** [comment]
It is important to inlclude the key/value `full_id_hash` in all datasets downstream of the enumerator as is done in the standard product pipeline. 

The hash-id affects all aspects the standard product pipeline (Marjorie and Mohammed will know the specifics). I personally know that the delivery system to ASF (aka the completeness evaluator) requires this in that if the hash-id is not correctly populated in acquisition lists and GUNWs, then the ASF delivery does not work. There are too many unintended side-effects in the pipeline for excluding this hash. Please use this.

Here is the [reference](https://github.com/aria-jpl/topsApp_pge/blob/develop/create_standard_product_s1.py#L287-L316) for how the hash should be generated.

full_id_hash: <hash_id>

In the naming convention of the file, Mohammed and team use the first four digits within the name per [here](https://github.com/aria-jpl/topsApp_pge/blob/develop/create_standard_product_s1.py#L618). Please follow this.

As you remove relevant data from the existing dataset name, please add the following to the ES doc:

- `AOITrack_id`
- `post-index` 
- `pre-index`
- `full_id_hash`

**Comment by riverma** [comment]
Hi @al-niessner - I concur with @cmarshak on his comment above, the closer to the way the standard-product enumerator generates the `id` name and associated metadata we can get, the better. Not only will it address this particular bug (I concurred with the HySDS team that shortening the `id` is currently the only way to avoid this issue - apart from modifying HySDS core code), but it would help downstream consumers be able to interoperate between standard and coseismic products if needed. 

So in summary:
- Modify `id` to be less than 255 byte limit
- Leverage the `id` format used by the standard product as much as possible (e.g. `S1-GUNW-acqlist-RM-M1S3-TN018-20191028T232823-20191004T232730-poeorb-00d5`), including:
   - keeping the `COSEISMIC` keyword
   - keeping the date range over which the acqlist applies
   - putting the first 4-digits of the `full_id_hash` at the end
- Add the following metadata to the acquisition list dataset ES, given we're shortening the `id` field by removing some of this information:
  - `AOITrack_id`
  - `post-index`
  - `pre-index`
  - `full_id_hash` <-- generate via [the standard product way](https://github.com/aria-jpl/topsApp_pge/blob/develop/create_standard_product_s1.py#L287-L316)

**Comment by al-niessner** [comment]
First, they will not be unique names but I will let you sort that out at a later date -- 4 bytes is not nearly enough to make all the information you have hash to a unique value. Date overlaps will happen because unlike the standard product it covers a much wider time period. Hence, then names will not be unique which is why the AOI track name is used.

Second, be clear on what you want the new acquisition list names to look like. Is it something like: 

S1-COSEISMIC-GUNW-acq-list-event-<start date>-<end date>-<4 byte hash>

Third, the name is already shorter than 255 characters. It is localizer that adds characters that causes the problem. Why are you limiting here what some other module breaks? If that module then adds more characters are you then going to come back here and reduce this name again?

Lastly, even shortening the name in the enumerator, the problem is not fixed because the localizer could/can still make a filename too long. The real solution is to fix the bug in the localizer. It should use a mapping of its ungainly long name into a hash that is always short like FAT32 file systems do it. In that way, it works always without having to change other modules when it decides to make filenames that are too long. Another option is to use subdirectories instead of a giant of a name. Either way, these are simple fixes that should be in the localizer and not spread out on modules independent of it (the localizer).

**Comment by cmarshak** [comment]
This is the naming convention we ideally want:

S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<reference_acquisition_datetime>-<secondary_acquisition_datetime>-poeorb-<first four digits of hash>

Here is an example:

S1-COSEISMIC-GUNW-acqlist-asc-R1S2-TN004-20161217T230745-20161123T230654-poeorb-a4bd

We don't need a totally unique name as we have the full hash ID and ES can handle, right @riverma? Still, all that data should be unique. If we can shorten that's fine.

Yes, there are numerous problems that need fixing. However, we are not rebuilding it now. That is not our task. We are finishing the pipeline and getting the automation to work (even if not the most robustly). 

The motivation of the above comments is to have our pipeline be easier to understand with reference to the standard product pipeline.

Further, putting the long AOITrack Id and pre/post index inside the ES document will allow us to connect the earthquake events and the rest of the processing pipeline.

**Comment by riverma** [comment]
Hi @al-niessner  -

> First, they will not be unique names but I will let you sort that out at a later date -- 4 bytes is not nearly enough to make all the information you have hash to a unique value. Date overlaps will happen because unlike the standard product it covers a much wider time period. Hence, then names will not be unique which is why the AOI track name is used.
> 
> Second, be clear on what you want the new acquisition list names to look like. Is it something like:
> 
> S1-COSEISMIC-GUNW-acq-list-event---<4 byte hash>
> 

Based on discussions with @cmarshak - the `<4 byte hash>` may be parsed downstream, so let's include that; however, you have leeway to ensure the filename is unique (i.e. create a small UID if you have to) but you'd have to ensure it falls under the constraint of 255 bytes _with the prepended_ `coseismic_product-s1gunw-slc_localizer__main-` string that HySDS core adds to the beginning when constructing a job working directory. That's the biggest constraint here. You can look at the standard product enumerator code to see any further examples. 

> Third, the name is already shorter than 255 characters. It is localizer that adds characters that causes the problem. Why are you limiting here what some other module breaks? If that module then adds more characters are you then going to come back here and reduce this name again?

Discussed below, but the problem is not in the localizer. 

> 
> Lastly, even shortening the name in the enumerator, the problem is not fixed because the localizer could/can still make a filename too long. The real solution is to fix the bug in the localizer. It should use a mapping of its ungainly long name into a hash that is always short like FAT32 file systems do it. In that way, it works always without having to change other modules when it decides to make filenames that are too long. Another option is to use subdirectories instead of a giant of a name. Either way, these are simple fixes that should be in the localizer and not spread out on modules independent of it (the localizer).

The code at hand (referenced above) is not within the localizer - it is within HySDS core. We'd have to do an upgrade to ARIA's deployed HySDS core modules to address this. I've noted this as a feature request to file a ticket with HySDS to address the issue of more flexible directory names. Unfortunately, for our task we don't have the time to wait for a fix and to deploy it (unless you can address it for us quickly). The standard product has much shorter file names and we should try to be as much in line with that model as possible. So in summary, I really think two fixes are needed: (1) shorter `id` fields within the acqlist to get us moving again, and (2) more flexibility in HySDS core in how job working directories are constructed from `id` fields.

**Comment by riverma** [comment]
Hi @al-niessner  -

> First, they will not be unique names but I will let you sort that out at a later date -- 4 bytes is not nearly enough to make all the information you have hash to a unique value. Date overlaps will happen because unlike the standard product it covers a much wider time period. Hence, then names will not be unique which is why the AOI track name is used.
> 
> Second, be clear on what you want the new acquisition list names to look like. Is it something like:
> 
> S1-COSEISMIC-GUNW-acq-list-event---<4 byte hash>
> 

Please see @cmarshak 's recommendation above. Though @cmarshak - ES doesn't like `_id` fields that are identical. I believe insertions can be rejected _if the shard that retains the doc is the same as the duplicate doc_

That being said, I don't think we need to worry about duplicates even with a `4 byte hash` - that's 36^4 = 1679616 possible combinations for 4 alphanumeric chars, and that in combination with two date timestamps makes the chances of duplicate IDs so small it doesn't justify additional brainstorming IMO.

> Third, the name is already shorter than 255 characters. It is localizer that adds characters that causes the problem. Why are you limiting here what some other module breaks? If that module then adds more characters are you then going to come back here and reduce this name again?

Discussed below, but the problem is not in the localizer. 

> 
> Lastly, even shortening the name in the enumerator, the problem is not fixed because the localizer could/can still make a filename too long. The real solution is to fix the bug in the localizer. It should use a mapping of its ungainly long name into a hash that is always short like FAT32 file systems do it. In that way, it works always without having to change other modules when it decides to make filenames that are too long. Another option is to use subdirectories instead of a giant of a name. Either way, these are simple fixes that should be in the localizer and not spread out on modules independent of it (the localizer).

The code at hand (referenced above) is not within the localizer - it is within HySDS core. We'd have to do an upgrade to ARIA's deployed HySDS core modules to address this. I've noted this as a feature request to file a ticket with HySDS to address the issue of more flexible directory names - so I don't disagree with you that HySDS core modules need patches. Unfortunately, for our task we don't have the time to wait for a fix and to deploy it (unless you can address it for us quickly). The standard product has much shorter file names and we should try to be as much in line with that model as possible. So in summary, I really think two fixes are needed: (1) shorter `id` fields within the acqlist to get us moving again - which we can do now, and (2) more flexibility in HySDS core in how job working directories are constructed from `id` fields - which we should put in for the future.

**Comment by al-niessner** [comment]
> Hi @al-niessner -
> 
> > First, they will not be unique names but I will let you sort that out at a later date -- 4 bytes is not nearly enough to make all the information you have hash to a unique value. Date overlaps will happen because unlike the standard product it covers a much wider time period. Hence, then names will not be unique which is why the AOI track name is used.
> > Second, be clear on what you want the new acquisition list names to look like. Is it something like:
> > S1-COSEISMIC-GUNW-acq-list-event---<4 byte hash>
> 
> Please see @cmarshak 's recommendation above. Though @cmarshak - ES doesn't like `_id` fields that are identical. I believe insertions can be rejected _if the shard that retains the doc is the same as the duplicate doc_
> 
> That being said, I don't think we need to worry about duplicates even with a `4 byte hash` - that's 36^4 = 1679616 possible combinations for 4 alphanumeric chars, and that in combination with two date timestamps makes the chances of duplicate IDs so small it doesn't justify additional brainstorming IMO.

Sorry, should have been 4 character not 4 byte hash.

I am not smart enough to read all of the comments and determine what you want. Please put it in a single line that I can understand like:

`S1-COSEISMIC-GUNW-acq-list-event-<start date/time>-<end date/time>-<4 character hash>` where date/time is in the form YYYYmmddHHMMSS or whatever it is that you want.

**Comment by al-niessner** [comment]
Given

`S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<reference_acquisition_datetime>-<secondary_acquisition_datetime>-poeorb-`

as basis for information, if more than one reference and more than one secondary, which times would you like to be used?

I do not see the ID (hash) anywhere in there.

**Comment by al-niessner** [comment]
Side note, yes all names have to unique.

**Comment by cmarshak** [comment]
> This is the naming convention we ideally want:
> 
> S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<reference_acquisition_datetime>-<secondary_acquisition_datetime>-poeorb-
> 
> Here is an example:
> 
> S1-COSEISMIC-GUNW-acqlist-asc-R1S2-TN004-20161217T230745-20161123T230654-poeorb-a4bd

This is ideally what we want. I think you could probably take out the asc/dsc and the R1S2, though the latter would help when differentiating between your "singular" enumerator scheme. 

So the datetime as on the SLC is

```<Year><Month><Day>T<Hour><Minute><Second>```

And I would consistently if possible take the first of the two reference/secondary scenes. Alphanumeric sorting should give the order the groups of scenes were acquired since they are on the same track.

**Comment by al-niessner** [comment]
> > This is the naming convention we ideally want:
> > S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<reference_acquisition_datetime>-<secondary_acquisition_datetime>-poeorb-
> > Here is an example:
> > S1-COSEISMIC-GUNW-acqlist-asc-R1S2-TN004-20161217T230745-20161123T230654-poeorb-a4bd
> 
> This is ideally what we want. I think you could probably take out the asc/dsc and the R1S2, though the latter would help when differentiating between your "singular" enumerator scheme.
> 
> So the datetime as on the SLC is
> 
> `<Year><Month><Day>T<Hour><Minute><Second>`
> 
> And I would consistently if possible take the first of the two reference/secondary scenes. Alphanumeric sorting should give the order the groups of scenes were acquired since they are on the same track.

starttime or endtime or starttime of first secondary and endtime of last reference to cover the entire time period of the list?

Is a4bd a constant?

**Comment by al-niessner** [comment]
Starting clean:

`S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<reference_acquisition_datetime>-<secondary_acquisition_datetime>-poeorb-`

time format: `<Year><Month><Day>T<Hour><Minute><Second>` with year being 4 digits.

**Comment by cmarshak** [comment]
> starttime or endtime or starttime of first secondary and endtime of last reference to cover the entire time period of the list?

Honestly, doesn't matter. I really like your suggestion of startime of first secondary and endtime of last reference. Very elegant.

> Is a4bd a constant?

No

>> In the naming convention of the file, Mohammed and team use the first four digits within the hash-id per [here](https://github.com/aria-jpl/topsApp_pge/blob/develop/create_standard_product_s1.py#L618). Please follow this.

Please use the above approach. Namely, generate the hash and then take the first 4 elements of it.

**Comment by riverma** [comment]
> Starting clean:
> 
> `S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<reference_acquisition_datetime>-<secondary_acquisition_datetime>-poeorb-`
> 
> time format: `<Year><Month><Day>T<Hour><Minute><Second>` with year being 4 digits.

So in summary, 👍  to "startime of first secondary and endtime of last reference." and the below, with the acquisition date time stamps having format: `<Year><Month><Day>T<Hour><Minute><Second>`:

### Template

`S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<first secondary_acquisition_datetime>-<last reference_acquisition_datetime>-poeorb-<first 4 chars of full_id_hash>`


### Example
`S1-COSEISMIC-GUNW-acqlist-asc-R1S2-TN004-20161217T230745-20161123T230654-poeorb-a4bd`

**Comment by al-niessner** [comment]
@riverma 

Your estimate of chances of overlap is a tad off because that is not how hashes work. You have a very long string (lots of data that go into making the hash) say 100 characters just for simplicity. Ignoring case and other characters, that gives you `26**100` possible inputs to your hasher or way bigger than 4 bytes (`2**32` or `16**8` to give a sense of scale). Hashing is then taking that huge set of input possibilities and mapping it back to a limited set of choices. So the probability of overlap (same hash for different input) comes from the large number of inputs and few possible  outputs. Given the length of the data you are putting into the hash, overlap is very likely. It gets even better if you realized my correction of 4 characters really means 2 bytes.

**Comment by al-niessner** [comment]
Side note, does not matter how big the original hash is/was if you are using just N bytes of it. That is just a hash of a hash with a really bad algorithm.

**Comment by al-niessner** [comment]
Next step. What do you want hashed?

### Template

`S1-COSEISMIC-GUNW-acqlist-<asc/dsc>-R<num_of_reference_scenes>S<number_of_secondary_scenes>-TN<track_number with leading zeros so its a 3 digit number>-<first secondary_acquisition_datetime>-<last reference_acquisition_datetime>-poeorb-<first 4 chars of full_id_hash>`

- time format: `<Year><Month><Day>T<Hour><Minute><Second>` with year being 4 digits.
- startime of first secondary and endtime of last reference
- hash items:  
    1. something
    2. something
    3. something

**Comment by cmarshak** [comment]
> Here is the [reference](https://github.com/aria-jpl/topsApp_pge/blob/develop/create_standard_product_s1.py#L287-L316) for how the hash should be generated.

Please use the above. Feel free to clean up, just have same output.  Concatenation of reference and secondary scenes (each sorted).

**Comment by al-niessner** [comment]
> > Here is the [reference](https://github.com/aria-jpl/topsApp_pge/blob/develop/create_standard_product_s1.py#L287-L316) for how the hash should be generated.
> 
> Please use the above. Feel free to clean up, just have same output. Concatenation of reference and secondary scenes (each sorted).

I cannot match its output because the enumerator formation is not the same as what the reference function is getting but probably not expecting given the code's current form.

It looks like an attempt to have all the reference and all the secondary SLC names concatenated by a space. Is this the goal or do you think the code is doing something else? Particularly interesting is that if it is a list of lists or tuples it does something else even weirder.

This brings back the point that if you want a hash and it has no real relevance to its input, particularly when truncating the hash, what difference does it really make that it reflects any other hash? Do you think that you can use the hash to find related items? If the latter, then you better spell out your inputs because I do not think what that code is doing is what you are saying you want.

**Comment by cmarshak** [comment]
What is the specific issue? Using the reference here is what I get:

```
import hashlib
def get_ifg_hash(master_slcs,  slave_slcs):

    master_ids_str = ''
    slave_ids_str = ''

    for slc in sorted(master_slcs):
        print('get_ifg_hash : master slc : %s' % slc)
        if isinstance(slc, tuple) or isinstance(slc, list):
            slc = slc[0]

        if master_ids_str == '':
            master_ids_str = slc
        else:
            master_ids_str += ' ' + slc

    for slc in sorted(slave_slcs):
        print('get_ifg_hash: slave slc : %s' % slc)
        if isinstance(slc, tuple) or isinstance(slc, list):
            slc = slc[0]

        if slave_ids_str == '':
            slave_ids_str = slc
        else:
            slave_ids_str += ' '+slc

    id_hash = hashlib.md5(json.dumps([
            master_ids_str,
            slave_ids_str
            ]).encode('utf8')).hexdigest()
    return id_hash

get_ifg_hash(['reference_1'], ['secondary_1', 'secondary_2'])
# ce46ff42c97a523e6eaae80a43269e09
```

**Comment by al-niessner** [comment]
Just pushed the code that cleanly does what you want because I know they are lists of strings and never anything else. The code you reference does some interesting stuff on if they are not strings. So, if you have data that is not a list of string it did not come from the enumerator and therefore we cannot generate the same hash.

Here is the short hand when you know they are a list of strings.

```
hashlib.md5(json.dumps([
        ' '.join (sorted (acqlist['master_scenes'])),
        ' '.join (sorted (acqlist['slave_scenes']))
        ]).encode('utf8')).hexdigest()
```
