### ISSUE TITLE
Configurable number of retries for Enumerator cronjob submission

### ISSUE THREAD

**Issue by riverma** [aria-jpl/coseismic_enumerator#9]
**Is your feature request related to a problem? Please describe.**
When testing the enumerator, in case the PGE crashes, currently HySDS retries job submissions to 5 attempts. This is normally okay, but frustrating in that we have to wait 5x longer than needed to read and debug a given `_stderr.txt` (each retry overwrites the file).

**Describe the solution you'd like**
A default of `5` retries specified in a configuration file that can be adjusted by hand if needed. Specifically [this code block](https://github.com/aria-jpl/coseismic_enumerator/blob/main/submit.py#L19-L27) most likely. 

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by al-niessner** [comment]
Cron is your retry. Do not have hysds retry.
